# Generated by Django 6.1 on 2026-09-01 06:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('category', models.CharField(choices=[('utility', 'Utility'), ('subscription', 'Subscription'), ('loan', 'Loan'), ('other', 'Other')], default='other', max_length=20)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=8)),
                ('previous_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('due_date', models.DateField()),
                ('recurrence', models.CharField(choices=[('monthly', 'Monthly'), ('yearly', 'Yearly'), ('weekly', 'Weekly'), ('one_time', 'One Time')], default='monthly', max_length=20)),
                ('is_subscription', models.BooleanField(default=False)),
                ('last_used_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('flagged', 'Flagged'), ('cancelled', 'Cancelled'), ('paid', 'Paid')], default='active', max_length=20)),
                ('notes', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['due_date'],
            },
        ),
        migrations.CreateModel(
            name='DecisionLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('agent_action', models.CharField(choices=[('auto_handled', 'Auto Handled'), ('flagged_for_review', 'Flagged for Review'), ('drafted_notification', 'Drafted Notification'), ('drafted_cancellation', 'Drafted Cancellation')], max_length=30)),
                ('reasoning', models.TextField()),
                ('draft_content', models.TextField(blank=True, null=True)),
                ('user_decision', models.CharField(blank=True, choices=[('approved', 'Approved'), ('rejected', 'Rejected'), ('pending', 'Pending')], default='pending', max_length=20, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('bill', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='decision_logs', to='bills.bill')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider_url', models.URLField(blank=True, null=True)),
                ('usage_notes', models.TextField(blank=True, null=True)),
                ('bill', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='subscription_detail', to='bills.bill')),
            ],
        ),
    ]
