# Generated by Django 6.1 on 2026-09-01 08:58

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bills', '0002_bill_owner'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='bill',
            name='confidence_score',
            field=models.FloatField(default=1.0, help_text='Recurring detection confidence (0.0 to 1.0)'),
        ),
        migrations.AddField(
            model_name='bill',
            name='merchant',
            field=models.CharField(blank=True, default='', max_length=150),
        ),
        migrations.AddField(
            model_name='bill',
            name='usage_frequency',
            field=models.CharField(blank=True, default='monthly', max_length=50),
        ),
        migrations.CreateModel(
            name='AIInsight',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('insight_type', models.CharField(choices=[('zombie', 'Zombie Subscription'), ('anomaly', 'Spending Anomaly'), ('savings', 'Savings Opportunity'), ('risk', 'Financial Risk'), ('price_increase', 'Price Increase')], max_length=30)),
                ('priority', models.CharField(choices=[('critical', 'Critical'), ('important', 'Important'), ('insight', 'Insight'), ('recommendation', 'Recommendation')], default='insight', max_length=20)),
                ('title', models.CharField(max_length=200)),
                ('message', models.TextField()),
                ('payload', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('dismissed', models.BooleanField(default=False)),
                ('bill', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='insights', to='bills.bill')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='insights', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PriceHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=8)),
                ('recorded_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('notes', models.CharField(blank=True, default='', max_length=255)),
                ('bill', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='price_history', to='bills.bill')),
            ],
            options={
                'ordering': ['-recorded_at'],
            },
        ),
    ]
