# Generated by Django 6.1 on 2026-09-02 04:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bills', '0003_bill_confidence_score_bill_merchant_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aiinsight',
            name='insight_type',
            field=models.CharField(choices=[('zombie', 'Zombie Subscription'), ('anomaly', 'Spending Anomaly'), ('savings', 'Savings Opportunity'), ('risk', 'Financial Risk'), ('price_increase', 'Price Increase'), ('warranty_expiring', 'Warranty Expiring')], max_length=30),
        ),
        migrations.AlterField(
            model_name='bill',
            name='category',
            field=models.CharField(choices=[('utility', 'Utility'), ('subscription', 'Subscription'), ('loan', 'Loan'), ('warranty', 'Warranty'), ('other', 'Other')], default='other', max_length=20),
        ),
        migrations.CreateModel(
            name='Warranty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('retailer', models.CharField(blank=True, default='', max_length=150)),
                ('purchase_date', models.DateField(blank=True, null=True)),
                ('return_window_days', models.PositiveIntegerField(blank=True, help_text='Retailer return/exchange window, in days, if shorter than the warranty itself', null=True)),
                ('claim_url', models.URLField(blank=True, help_text='Manufacturer/retailer warranty claim or support page', null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('bill', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='warranty_detail', to='bills.bill')),
            ],
        ),
    ]
