# Generated by Django 6.1 on 2026-09-02 04:44

import django.core.validators
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bills', '0004_alter_aiinsight_insight_type_alter_bill_category_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='bill',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=8, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))]),
        ),
        migrations.AlterField(
            model_name='bill',
            name='previous_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))]),
        ),
        migrations.AddIndex(
            model_name='bill',
            index=models.Index(fields=['owner', 'due_date'], name='bill_owner_due_date_idx'),
        ),
        migrations.AddIndex(
            model_name='bill',
            index=models.Index(fields=['owner', 'category', 'status'], name='bill_owner_cat_status_idx'),
        ),
    ]
